import Head from "next/head";
import {
  Container,
  Main,
  Title,
  Description,
} from "@/components/sharedstyles";

export default function Home() {
  return (
    <Container>
      <Head>
        <title>Dança dos segredos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        <Title>
          Dança dos Segredos
        </Title>

        <Description>
          Local de ajuda
        </Description>
      </Main>
    </Container>
  );
}
